### ISSUE TITLE
PHP后台返回空对象使用[ ]如何容错？

### ISSUE THREAD

**Issue by ydmmocoo** [getActivity/GsonFactory#1]
空对象本来应该返回null或者{ }的，但是PHP后台返回成了[ ]，如何容错？

**Comment by getActivity** [comment]
这块还没有兼容到，但是现在已经在做了

**Comment by xmlxin** [comment]
php 空对象返回的确实是[],不知道php这个语言为什么会这样

**Comment by getActivity** [comment]
小伙子，这块的容错已经加上了，更新一下框架版本即可。
