### ISSUE TITLE
关于JsonCallback关联功能的优化建以

### ISSUE THREAD

**Issue by op123355569** [getActivity/GsonFactory#15]
## 建议收集

* issue 是否有人曾提过类似的问题？（必答项，一旦出现重复提问我将不会再次解答）
    否

* 你觉得框架有什么不足之处？（必答项，你可以描述框架有什么令你不满意的地方）
    CollectionTypeAdapterFactory、ReflectiveTypeAdapterFactory 在 create 方法中，return TypeAdapter前未调用【setReflectiveType】方法，导致如果是整个类或者这个List转换错误的情况下，JsonCallback回调中前两个值都为null。
    举例：
    `
    String value = "[{\"name\":\"张三\"}]";
    IceVo iceVo = ...(转换代码)
    `
    
    `
    String value2 = "{\"name\":\"张三\"}";
    List<IceVo> list = ...(转换代码)
    `

    虽然应用到的可能性比较小，但是我觉得可以更完善一点吧。

* 你觉得该怎么去完善会比较好？（非必答项，你可以提供一下自己的想法或者做法供作者参考）
    CollectionTypeAdapterFactory、ReflectiveTypeAdapterFactory 在 create 方法中，return TypeAdapter前调用【setReflectiveType】方法

**Comment by getActivity** [comment]
多谢小伙子的提醒，问题已经纠正了。

**Comment by getActivity** [comment]
[GsonFactory-6.0.aar.zip](https://github.com/getActivity/GsonFactory/files/8058019/GsonFactory-6.0.aar.zip)

**Comment by getActivity** [comment]
考虑到问题影响范围比较小，所以不会立即发布远程依赖，你要是着急可以先用这个包。

**Comment by getActivity** [comment]
issue 的话我先关闭了，到时候有问题再联系我。
