### ISSUE TITLE
Gson 2.9.0兼容性问题

### ISSUE THREAD

**Issue by Key-CN** [getActivity/GsonFactory#16]
## 问题描述
Gson 2.9.0
ConstructorConstructor()构造多了一个参数
而GsonFactory用的是单构造的ConstructorConstructor()，要不要考虑兼容一下
Gson无法代码判断版本号，这个兼容只能用反射实现？判断这个构造方法是一个参数还是两个参数？
想不到什么更好的方案

* 框架版本：com.github.getActivity:GsonFactory:5.2

* 问题描述：
ConstructorConstructor constructor = new ConstructorConstructor(INSTANCE_CREATORS);

* 复现步骤：使用'com.google.code.gson:gson:2.9.0'

* 是否必现：是

**Comment by po1xiao** [comment]
可以的兄弟，我正在编写这呢，发着这个问题被你提了，我再补充一下：

**Comment by getActivity** [comment]
小伙子，问题已经修复了，更新到 6.0 版本即可。

**Comment by Key-CN** [comment]
这效率极致了！！！

**Comment by LxzBUG** [comment]
@getActivity 请问什么时候发布到jitpack呢
