### ISSUE TITLE
适配gson2.9.1

### ISSUE THREAD

**Issue by Reginer** [getActivity/GsonFactory#19]
## 使用gson2.9.1崩溃

* 框架版本【必填】：6.2

![image](https://user-images.githubusercontent.com/12568257/183385042-f27c7ec3-6dda-4639-824e-242731aadf84.png)
![image](https://user-images.githubusercontent.com/12568257/183385078-e8b2dfe1-ad4e-479f-ada8-14e0a8513056.png)

**Comment by getActivity** [comment]
[GsonFactory-6.3.aar.zip](https://github.com/getActivity/GsonFactory/files/9290606/GsonFactory-6.3.aar.zip)

**Comment by getActivity** [comment]
@Reginer 多谢小伙子的提醒，已经做兼容处理了

**Comment by Reginer** [comment]
赞，响应好迅速

**Comment by LxzBUG** [comment]
@getActivity 请问什么时候发布到jitpack呢

**Comment by getActivity** [comment]
@LxzBUG 已经发布到 JitPack 了，再看一下

**Comment by Reginer** [comment]
6.2的依赖好像搞没了，https://jitpack.io/#getActivity/GsonFactory build.log里面文件丢了，重新编译一下 ？
![image](https://user-images.githubusercontent.com/12568257/187335123-85711865-bca3-4025-92f2-fe2ebdba9ae3.png)

**Comment by getActivity** [comment]
<img width="786" alt="image" src="https://user-images.githubusercontent.com/28616817/187363256-946604d7-05f5-4e26-b8fa-3b9a4ef7f828.png">

@Reginer 我这边是可以正常打开的，[https://jitpack.io/com/github/getActivity/GsonFactory/6.2/build.log](https://jitpack.io/com/github/getActivity/GsonFactory/6.2/build.log)

**Comment by Reginer** [comment]
> <img alt="image" width="786" src="https://user-images.githubusercontent.com/28616817/187363256-946604d7-05f5-4e26-b8fa-3b9a4ef7f828.png">
> 
> @Reginer 我这边是可以正常打开的，https://jitpack.io/com/github/getActivity/GsonFactory/6.2/build.log

嗯，现在可以了，库重新构建了，构建时间变成8.30了
