### ISSUE TITLE
希望能支持一下，int会自动转为double的问题，

### ISSUE THREAD

**Issue by BugRui** [getActivity/GsonFactory#2]

**Comment by BugRui** [comment]
我是在Retrofit里面使用，提交参数的时候，因为是不确定类型，后端需要指定类型，我用了object，传了一个int，结果被转成了double

**Comment by getActivity** [comment]
小伙子，你只能确定好类型，否则 Gson 没办法按照你的想法来。还有框架是处理 Gson 解析容错的，这个问题不属于容错的问题，应该属于数据匹配的问题。

**Comment by BugRui** [comment]
场景是这样的，接口返回一个数组，有key和value，value可能是数字可能是字符串，但是后端要求，value是数字的时候必须传数字，字符串的时候传字符串格式

发自我的iPhone
