### ISSUE TITLE
后台成功与失败返回类型不一致的问题

### ISSUE THREAD

**Issue by billdizl** [getActivity/GsonFactory#21]
## 建议收集

* issue 是否有人曾提过类似的问题？【必答】否

* 你觉得框架有什么不足之处？【必答】 后台返回的错误数据结构与实体类不一致,如果使用了该lib,那么就会被容错了,获取到的对象是空的,比如后台返回的正确的是{"code":200,
"result":{"banner":"1"} }而错误的是{"code":500,
"result":"网络出现了异常"},我需要吐司出来这个result数据,那么使用该lib 我获取到的result就是空的

* 你觉得该怎么去完善会比较好？【非必答】
* 是否可以提交一个接口让开发者单独对其做出处理?

**Comment by getActivity** [comment]
小伙子，你想过一个问题没有？result 字段要定义成什么类型的？

**Comment by getActivity** [comment]
超过三天没有响应，自动关闭此 issue。
