### ISSUE TITLE
json名字中带特殊符表情比如😁（unicode）的数据是否有容错处理

### ISSUE THREAD

**Issue by Lans** [getActivity/GsonFactory#23]
#### 问题描述

* json名字中带特殊符表情比如😁（unicode）的数据是否有容错处理

#### 请回答

* issue 是否有人曾提过类似的问题？【必答】否

* 框架文档是否有提及到此问题？【必答】：否

**Comment by getActivity** [comment]
如果用了会有什么问题？

**Comment by Lans** [comment]
json解析报错，崩溃呗

**Comment by Lans** [comment]
目前解决方案 GsonBuilder().disableHtmlEscaping().create()

**Comment by getActivity** [comment]
你把会报错的 json 发来我试试看

**Comment by Lans** [comment]
试试这个{"string":"轮子\u6211\u662F\u5730\u7403\uD83C\uDF0D"}

**Comment by getActivity** [comment]
<img width="593" alt="image" src="https://user-images.githubusercontent.com/28616817/221778190-80c17afd-cb01-4d8f-a234-ad137fd4ff06.png">

**Comment by getActivity** [comment]
小伙子，我试过了没有问题

**Comment by Lans** [comment]
`   data class Name(val name: String)

    override fun initRequestData() {
        // 模拟获取数据
//        mViewModel.getData()

        val ss= "{\"name\":轮子\\u6211\\u662F\\u5730\\u7403\\uD83C\\uDF0D}"
//        val ss = "{\"name\":An 😀awesome 😃string with a few 😉emojis}"
        val fromJson = GsonFactory.getSingletonGson().fromJson(ss, Name::class.java)
        Log.e("test",fromJson.toString())
    }`
![image](https://user-images.githubusercontent.com/16605722/221794328-68acd8f6-32a2-4ff5-9079-1b421003f36b.png)
解析完打印的时候咋会报错

**Comment by getActivity** [comment]
```text
"{\"name\":轮子\\u6211\\u662F\\u5730\\u7403\\uD83C\\uDF0D}"
```

**Comment by Lans** [comment]
先关了吧，找不到源数据了，下次碰到再开😅
