### ISSUE TITLE
建议适配kotlin默认值

### ISSUE THREAD

**Issue by Lanxiong** [getActivity/GsonFactory#24]
#### 建议收集

* issue 是否有人曾提过类似的问题？【必答】 #4  有人提出过类似的疑问

* 框架文档是否有提及到此问题？【必答】：否

* 你觉得框架有什么不足之处？【必答】

框架的容错特性确实很不错  考虑到目前kotlin开发占比很高 
而kotlin在定义data class时候给默认值是比较常规的做法  
很大一部分人还是通过Gson来配合retrofit 但目前的Gson不完全支持默认值  
核心代码：

```java
Object fieldValue = typeAdapter.read(reader);
if (fieldValue != null || !isPrimitive) {
    field.set(value, fieldValue);
}
```

当为非基本类型时候 会强制赋值 导致默认值失效
如果可以适配kotlin的默认值情况  能解决  设置了默认值 还是非空类型 还要必须判空的情况

* 你觉得该怎么去完善会比较好？【非必答】

建议：如果强制更改这一段赋值逻辑 可能就不是“原汁原味”的Gson了 改动有点大 不一定大家都能接受
所以在初始化的时候给一个配置 可以开启支持kotlin默认值 可能是比较好的做法
核心代码：

```java
Object fieldValue = typeAdapter.read(reader);
if (fieldValue != null) {
    field.set(value, fieldValue);
} else if (!isPrimitive) {
    if (field.get(value) == null) {
        field.set(value, null);
    }
}
```

**Comment by getActivity** [comment]
小伙子，那你有没有想过有一种情况，后台有给你返回某个字段，但是这个字段的值是空，不知道你是否思考过有这种情况？

```json
{
    "key": null
}
```

**Comment by Lanxiong** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Lanxiong** [comment]
考虑过的 常用的三种 String Object List引用类型 
业务层面来说，String的null和“”几乎没有区别，List的null和空集合几乎也没有区别，都是这个字段没有内容。仅有是不是已经初始过的区别 。Object的null和有值还是有区别的，不过默认值一般都给null。 当然可能也有部分场景像你说的null也代表一种意思 使用者完全可以把默认值设置为null 也不冲突。 由于有不同的场景需求，所以觉得这个适配kotlin默认值的功能可以作为一个配置项 可以选择开启 也可以不选择 用原配的Gson就好  Moshi我也用过 安全风险太低了 定义为非空类型 后台万一给个null就崩了 每个都是非空类型  那写起来都是?.?.也不对劲  掘金里面也有不少文章写适配默认值不让null覆盖的 应该也是不少人的需求吧

**Comment by Lanxiong** [comment]
你说的可能还有基本类型的null情况 那开发者定义了非空有默认值，不需要null的情况 必然是默认值已经包含了null的业务场景 非得要null的场景 定义为可空就好了 还是有选择空间的

**Comment by getActivity** [comment]
> 考虑过的 常用的三种 String Object List引用类型 业务层面来说，String的null和“”几乎没有区别，List的null和空集合几乎也没有区别，都是这个字段没有内容。仅有是不是已经初始过的区别 。Object的null和有值还是有区别的，不过默认值一般都给null。 当然可能也有部分场景像你说的null也代表一种意思 使用者完全可以把默认值设置为null 也不冲突。 由于有不同的场景需求，所以觉得这个适配kotlin默认值的功能可以作为一个配置项 可以选择开启 也可以不选择 用原配的Gson就好 Moshi我也用过 安全风险太低了 定义为非空类型 后台万一给个null就崩了 每个都是非空类型 那写起来都是?.?.也不对劲 掘金里面也有不少文章写适配默认值不让null覆盖的 应该也是不少人的需求吧

小伙子，劳烦贴一下掘金这块的文章，我看看大伙的需求是什么样的

**Comment by getActivity** [comment]
还有小伙子，关于你提供的代码，我有一个疑惑的问题

```java
Object fieldValue = typeAdapter.read(reader);
if (fieldValue != null) {
    field.set(value, fieldValue);
} else if (!isPrimitive) {
    if (field.get(value) == null) {
        field.set(value, null);
    }
}
```

* 下面这段逻辑代码不是废话？

```java
if (field.get(value) == null) {
    field.set(value, null);
}
```

**Comment by Lanxiong** [comment]
哈哈哈 是的 那段代码是我抄来的  我自己测的时候也发现了 感觉那段代码很奇怪 确实就是不为null时候赋值 一个意思

**Comment by cxf910714** [comment]
> > 考虑过的 常用的三种 String Object List引用类型 业务层面来说，String的null和“”几乎没有区别，List的null和空集合几乎也没有区别，都是这个字段没有内容。仅有是不是已经初始过的区别 。Object的null和有值还是有区别的，不过默认值一般都给null。 当然可能也有部分场景像你说的null也代表一种意思 使用者完全可以把默认值设置为null 也不冲突。 由于有不同的场景需求，所以觉得这个适配kotlin默认值的功能可以作为一个配置项 可以选择开启 也可以不选择 用原配的Gson就好 Moshi我也用过 安全风险太低了 定义为非空类型 后台万一给个null就崩了 每个都是非空类型 那写起来都是?.?.也不对劲 掘金里面也有不少文章写适配默认值不让null覆盖的 应该也是不少人的需求吧
> 
> 小伙子，劳烦贴一下掘金这块的文章，我看看大伙的需求是什么样的
kotlin 默认值确实狠有必要实现的，
最近后台返回数据就是很骚,把我自己定义的默认值都给覆盖了，搞得每次用到?.判断：
val isCheck: Boolean = false  返回null
val check: String= ""     返回null
val check: List<String>  返回null

**Comment by maydaynicko** [comment]
+1，现在kotlin应该是主流android开发语言了，data class的默认值支持是很有必要的

**Comment by BugFactoty** [comment]
**0-0  这几天被gson和kotlin搞吐了**

**Comment by GuangNian10000** [comment]
现在后端就是php，返回的数据类型杂的要死，同建议适配kotlin默认值

**Comment by getActivity** [comment]
收到，多谢小伙子们的反馈，我将在近期适配这个问题。

**Comment by getActivity** [comment]
@Lanxiong @BugFactory9527 @GuangNian10000 @maydaynicko 小伙子们，框架已经在 [6.6](https://github.com/getActivity/GsonFactory/releases/tag/6.6) 版本上面已经处理了该问题，升级一下版本即可。

**Comment by Tsreadlly** [comment]
轮子哥牛逼

**Comment by po1xiao** [comment]
轮子哥牛逼

**Comment by NBXXF** [comment]
可以尝试这个,并且10倍速度提升 https://github.com/NBXXF/gson_plugin

**Comment by NBXXF** [comment]
> ## 【警告：请务必按照 issue 模板填写，不要抱有侥幸心理，一旦发现 issue 没有按照模板认真填写，一律直接关闭】
> #### 建议收集
> * issue 是否有人曾提过类似的问题？【必答】 [服务端没有返回相应的字段数据 #4](https://github.com/getActivity/GsonFactory/issues/4)  有人提出过类似的疑问
> * 框架文档是否有提及到此问题？【必答】：否
> * 你觉得框架有什么不足之处？【必答】
> 
> 框架的容错特性确实很不错 考虑到目前kotlin开发占比很高 而kotlin在定义data class时候给默认值是比较常规的做法 很大一部分人还是通过Gson来配合retrofit 但目前的Gson不完全支持默认值 核心代码：
> 
> ```java
> Object fieldValue = typeAdapter.read(reader);
> if (fieldValue != null || !isPrimitive) {
>     field.set(value, fieldValue);
> }
> ```
> 
> 当为非基本类型时候 会强制赋值 导致默认值失效 如果可以适配kotlin的默认值情况 能解决 设置了默认值 还是非空类型 还要必须判空的情况
> 
> * 你觉得该怎么去完善会比较好？【非必答】
> 
> 建议：如果强制更改这一段赋值逻辑 可能就不是“原汁原味”的Gson了 改动有点大 不一定大家都能接受 所以在初始化的时候给一个配置 可以开启支持kotlin默认值 可能是比较好的做法 核心代码：
> 
> ```java
> Object fieldValue = typeAdapter.read(reader);
> if (fieldValue != null) {
>     field.set(value, fieldValue);
> } else if (!isPrimitive) {
>     if (field.get(value) == null) {
>         field.set(value, null);
>     }
> }
> ```

可以尝试这个,并且10倍速度提升 https://github.com/NBXXF/gson_plugin

**Comment by NBXXF** [comment]
> [Kotlin 也有json解析问题？](https://juejin.cn/post/7029323033391169572)
> 
> [kotlin gson反序列化默认值失效](https://juejin.cn/post/6844903743901679623)
> 
> [Gson 和 Kotlin Data Class 的避坑指南](https://juejin.cn/post/6908391430977224718)
> 
> [Gson 支持 Kotlin 空安全的一种尝试](https://juejin.cn/post/6844904052183007245)
> 
> 这几篇是吐槽默认值失效的
> 
> 搜 Gson kotlin 这两关键词有不少文章都在讲通过一些方法如何做到默认值有效 但是都会有大量的额外模板代码 不是很实用

可以尝试这个,并且10倍速度提升 https://github.com/NBXXF/gson_plugin
