### ISSUE TITLE
容错范围

### ISSUE THREAD

**Issue by tangyixin01** [getActivity/GsonFactory#25]
#### 问题描述

* 请描述一下你的疑惑【必填】：期待的是bean但是返回的是空字符串容错失败了。

#### 请回答

* issue 是否有人曾提过类似的问题？【必答】否

* 框架文档是否有提及到此问题？【必答】：是
hello，轮子哥，很感谢能开源这么多项目。我在使用容错项目前看到了项目简介容错支持bean。或者说是不兼容的类型直接不解析。我遇见的问题是这样的：retrofit请求使用的gson解析，baseresponse中泛型data对象有时候在接口校验失败之后，后台原先返回的data就会变成空字符串，这时候就会有问题因为baseresponse里面的泛型data通常是传一个bean进去，导致了解析异常报错。使用本框架还是没有容错，请问轮子哥这个场景在不在本框架的容错范围之内。

**Comment by tangyixin01** [comment]
项目里面的所有网络请求都是基于协程，刚看了下容错框架里面有一些try catch，可能是对于协程来说try catch失效，导致的容错失败？

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，打回的原因如下：

* 这个问题属于 bug，不能提疑问 issue 单，请提 bug issue 单

请重新提一个 issue 并纠正以上问题
