### ISSUE TITLE
能否通过getDelegateAdapter方法给所有TypeAdapter都套层代理，出错时直接跳到下一个呢

### ISSUE THREAD

**Issue by wcy0312808** [getActivity/GsonFactory#26]
#### 问题描述
大佬您好：
在阅读源码时，偶然发现在Gson.class下，跟getAdapter同级有一个getDelegateAdapter的方法，它的作用是可以给所有的TypeAdapter设置代理类，这样就可以拦截TypeAdapter出错时的动作，比如下面类似代码：

```java
{
    val gson = GsonBuilder().registerTypeAdapterFactory(StrongTypeAdapterFactory()).create()
    class StrongTypeAdapterFactory : TypeAdapterFactory {
        override fun <T> create(gson: Gson, type: TypeToken<T>): TypeAdapter<T> {
            // 给每一个目标TypeAdapter都嵌套一个代理，可以主动拦截其结果
            val adapter: TypeAdapter<T> = gson.getDelegateAdapter(this, type)

            return object : TypeAdapter<T>() {
                @Throws(IOException::class)
                override fun write(out: JsonWriter, value: T?) {
                    adapter.write(out, value)
                }

                @Throws(IOException::class)
                override fun read(reader: JsonReader): T? {
                    return try {
                        // 原始目标adapter反序列化
                        adapter.read(reader)
                    } catch (e: Throwable) {
                        // 只要有报错的并且还有下一个就执行跳过操
                        if (reader.hasNext()) {
                            reader.skipValue()
                        }
                        null
                    }
                }
            }
        }
    }
}
```

这样是不是就能简单粗暴的搞定所有的容错呢。

#### 请回答

* issue 是否有人曾提过类似的问题？【必答】 没有

* 框架文档是否有提及到此问题？【必答】：否

**Comment by wcy0312808** [comment]
`  class StrongTypeAdapterFactory : TypeAdapterFactory {
    override fun <T> create(gson: Gson, type: TypeToken<T>): TypeAdapter<T> {
        // 给每一个目标TypeAdapter都嵌套一个代理，可以主动拦截其结果
        val adapter: TypeAdapter<T> = gson.getDelegateAdapter(this, type)

        return object : TypeAdapter<T>() {
            @Throws(IOException::class)
            override fun write(out: JsonWriter, value: T?) {
                adapter.write(out, value)
            }

            @Throws(IOException::class)
            override fun read(reader: JsonReader): T? {
                return try {
                    adapter.read(reader)
                } catch (e: Throwable) {
                    // 只要有报错的并且还有下一个就执行跳过操作
                    if (reader.hasNext()) {
                        reader.skipValue()
                    }
                    null
                }
            }
        }
    }
} `

**Comment by wcy0312808** [comment]
不知道怎么回事，代码粘贴一直有问题，劳烦作者您尝试阅读下了

**Comment by getActivity** [comment]
小伙子，如果我想知道解析出错的类名和字段名，你这种方式还能实现么？

**Comment by wcy0312808** [comment]
> 小伙子，如果我想知道解析出错的类名和字段名，你这种方式还能实现么？

感谢您的回复我刚刚看了一下，在catch中，

**Comment by getActivity** [comment]
小伙子，我测试了一下，`reader.path` 只会输出字段的名称，如果我想要知道类名+字段名称呢？该怎么做？

**Comment by wcy0312808** [comment]
> 小伙子，我测试了一下，`reader.path` 只会输出字段的名称，在实际开发中还是不够明确，因为很多字段名会出现重复的情况，如果我想要知道类名+字段名称呢？该怎么做？

我从Gson中的TypeToken中获取了启发，每次catch时，可以从目标TypeAdapter中获取父类的类型，获取到具体字段的类型

**Comment by wcy0312808** [comment]
> > 小伙子，我测试了一下，`reader.path` 只会输出字段的名称，在实际开发中还是不够明确，因为很多字段名会出现重复的情况，如果我想要知道类名+字段名称呢？该怎么做？
> 
> 我从Gson中的TypeToken中获取了启发，每次catch时，可以从目标TypeAdapter中获取父类的类型，获取到具体字段的类型。具体代码如下：
> 
> ```java
> adapter.javaClass.genericSuperclass.typeName
> ```
> 
> 但是经过测试我发现只能获取到基本数据类型的类型，如果是组合类型是获取不到的，但经过debug后，我发现ReflectiveTypeAdapter中的中的constructor中有一个rawType中存在具体的类型，所以我通过反射去尝试获取了下：
> 
> ```java
>  if (adapter is ReflectiveTypeAdapterFactory.Adapter) {
>                         val field = adapter.javaClass.getDeclaredField("constructor")
>                         field.isAccessible = true
>                         val constructor = field.get(adapter)
>                         constructor.javaClass.genericInterfaces.forEach {
>                             if (it is ParameterizedType) {
>                                 for (type in it.actualTypeArguments) {
>                                     println("T === $type")
>                                 }
>                             }
>                         }
>                     }
> ```
> 
> 打印出来一个T，而且没有拿到rawType，但我感觉还是有可能去获取的，但是目前还没找到合适方法

其实大佬，我项目中更多的需求是在解析中不会因为某个字段的解析而导致整个页面无法展示，做一个最简单的兼容就可以了，对于具体字段或者类型的获取需求并不是很强烈，您是这方面的大佬，想问下通过这种简单粗暴的方案可以实现吗？

**Comment by getActivity** [comment]
小伙子，我看了你这种方式，理论上是可以实现的，但是我这边没有投入到线上验证过，建议你多做测试，至于有没有问题我不敢给你做保证。

**Comment by wcy0312808** [comment]
> 小伙子，我看了你这种方式，理论上是可以实现的，但是我这边没有投入到线上验证过，建议你多做测试，至于有没有问题我不敢给你做保证。

好的，明白了，感谢大佬回复

**Comment by NBXXF** [comment]
> ## 【警告：请务必按照 issue 模板填写，不要抱有侥幸心理，一旦发现 issue 没有按照模板认真填写，一律直接关闭】
> #### 问题描述
> 大佬您好： 在阅读源码时，偶然发现在Gson.class下，跟getAdapter同级有一个getDelegateAdapter的方法，它的作用是可以给所有的TypeAdapter设置代理类，这样就可以拦截TypeAdapter出错时的动作，比如下面类似代码：
> 
> ```java
> {
>     val gson = GsonBuilder().registerTypeAdapterFactory(StrongTypeAdapterFactory()).create()
>     class StrongTypeAdapterFactory : TypeAdapterFactory {
>         override fun <T> create(gson: Gson, type: TypeToken<T>): TypeAdapter<T> {
>             // 给每一个目标TypeAdapter都嵌套一个代理，可以主动拦截其结果
>             val adapter: TypeAdapter<T> = gson.getDelegateAdapter(this, type)
> 
>             return object : TypeAdapter<T>() {
>                 @Throws(IOException::class)
>                 override fun write(out: JsonWriter, value: T?) {
>                     adapter.write(out, value)
>                 }
> 
>                 @Throws(IOException::class)
>                 override fun read(reader: JsonReader): T? {
>                     return try {
>                         // 原始目标adapter反序列化
>                         adapter.read(reader)
>                     } catch (e: Throwable) {
>                         // 只要有报错的并且还有下一个就执行跳过操
>                         if (reader.hasNext()) {
>                             reader.skipValue()
>                         }
>                         null
>                     }
>                 }
>             }
>         }
>     }
> }
> ```
> 
> 这样是不是就能简单粗暴的搞定所有的容错呢。
> 
> #### 请回答
> * issue 是否有人曾提过类似的问题？【必答】 没有
> * 框架文档是否有提及到此问题？【必答】：否

这种似乎效率很低 每次都要创建
