### ISSUE TITLE
[Bug]：com.google.gson.internal.ConstructorConstructor$9.construct (ConstructorConstructor.java:262)

### ISSUE THREAD

**Issue by billdizl** [getActivity/GsonFactory#28]
### 框架版本【必填】

6.5

### 问题描述【必填】

com.google.gson.internal.ConstructorConstructor$9.construct (ConstructorConstructor.java:262)
com.hjq.gson.factory.element.ReflectiveTypeAdapter.read (ReflectiveTypeAdapter.java:58)
com.hjq.gson.factory.element.ReflectiveTypeUtils$1.read (ReflectiveTypeUtils.java:111)
com.hjq.gson.factory.element.ReflectiveTypeAdapter.read (ReflectiveTypeAdapter.java:71)
com.hjq.gson.factory.element.TypeAdapterRuntimeTypeWrapper.read (TypeAdapterRuntimeTypeWrapper.java:35)
com.hjq.gson.factory.element.CollectionTypeAdapter.read (CollectionTypeAdapter.java:62)
com.hjq.gson.factory.element.CollectionTypeAdapter.read (CollectionTypeAdapter.java:23)
com.hjq.gson.factory.element.ReflectiveTypeUtils$1.read (ReflectiveTypeUtils.java:111)
com.hjq.gson.factory.element.ReflectiveTypeAdapter.read (ReflectiveTypeAdapter.java:71)
com.hjq.gson.factory.element.TypeAdapterRuntimeTypeWrapper.read (TypeAdapterRuntimeTypeWrapper.java:35)
com.hjq.gson.factory.element.CollectionTypeAdapter.read (CollectionTypeAdapter.java:62)
com.hjq.gson.factory.element.CollectionTypeAdapter.read (CollectionTypeAdapter.java:23)
com.google.gson.Gson$FutureTypeAdapter.read (Gson.java:1367)
com.hjq.gson.factory.element.ReflectiveTypeUtils$1.read (ReflectiveTypeUtils.java:111)
com.hjq.gson.factory.element.ReflectiveTypeAdapter.read (ReflectiveTypeAdapter.java:71)
com.hjq.gson.factory.element.TypeAdapterRuntimeTypeWrapper.read (TypeAdapterRuntimeTypeWrapper.java:35)
com.hjq.gson.factory.element.CollectionTypeAdapter.read (CollectionTypeAdapter.java:62)
com.hjq.gson.factory.element.CollectionTypeAdapter.read (CollectionTypeAdapter.java:23)
com.hjq.gson.factory.element.ReflectiveTypeUtils$1.read (ReflectiveTypeUtils.java:111)
com.hjq.gson.factory.element.ReflectiveTypeAdapter.read (ReflectiveTypeAdapter.java:71)
com.google.gson.Gson.fromJson (Gson.java:1227)
com.google.gson.Gson.fromJson (Gson.java:1137)
com.google.gson.Gson.fromJson (Gson.java:1047)
com.google.gson.Gson.fromJson (Gson.java:1014)

### 复现步骤【必填】

无

### 是否必现【必填】

否

### 项目 targetSdkVersion【必填】

31

### 出现问题的手机信息【必填】

Galaxy A02

### 出现问题的安卓版本【必填】

7

### 问题信息的来源渠道【必填】

其他渠道

### 是部分机型还是所有机型都会出现【必答】

全部

### 框架最新的版本是否存在这个问题【必答】

是

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

否

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

### 是否可以通过 Demo 来复现该问题【必答】

否

### 提供截图或视频

![c2fd3726cc037bd23fad2f71f8b84796](https://github.com/getActivity/GsonFactory/assets/30317994/a4d9644a-30cc-4b72-8ab7-30aa5744650b)

**Comment by getActivity** [comment]
<img width="667" alt="image" src="https://github.com/getActivity/GsonFactory/assets/28616817/5552afd2-b7eb-478e-9984-f133ab664abe">

**Comment by getActivity** [comment]
<img width="684" alt="image" src="https://github.com/getActivity/GsonFactory/assets/28616817/e4c30e61-6372-4986-a10a-0509fd327f6e">

**Comment by getActivity** [comment]
小伙子，结合报错的代码和从报错提示来看，这个问题应该是你的应用内存不足导致的，Gson 在反射对象的时候需要申请开辟新的内存空间，结果发现内存不够了，系统就会抛出异常，所以这个问题并不是框架的问题。
