### ISSUE TITLE
[建议]：Gson 框架转义问题

### ISSUE THREAD

**Issue by spring1999** [getActivity/GsonFactory#29]
### 你觉得框架有什么不足之处？【必答】

这框架的转义有一点问题，详情见
https://blog.csdn.net/ifengfan/article/details/88553819

### issue 是否有人曾提过类似的建议？【必答】

否

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### 你觉得该怎么去完善会比较好？【非必答】

https://blog.csdn.net/ifengfan/article/details/88553819

**Comment by getActivity** [comment]
小伙子，我没有办法 Get 到你的点子，你是遇到什么问题了吗？或者你能说一下为什么要改成那样吗？

**Comment by getActivity** [comment]
超过两个星期没有响应，自动关闭此 issue。
