### ISSUE TITLE
请问一下这样处理可以吗？

### ISSUE THREAD

**Issue by shaohui93** [getActivity/GsonFactory#3]
addConverterFactory(GsonConverterFactory.create(GsonBuilder().create()))，GsonBuilder().create() 这个更换成类库里的Gson实例，可以处理容错么？比如int的字段，但是后台返回的小数！

**Comment by getActivity** [comment]
可以的小伙子

**Comment by getActivity** [comment]
如果客户端定义的是整数，但后台返回浮点数，框架就对数值进行取整

**Comment by shaohui93** [comment]
感谢🙏
