### ISSUE TITLE
[建议]：我想去掉这样的警告打印<init> argument 4 has type int, got null

### ISSUE THREAD

**Issue by GuangNian10000** [getActivity/GsonFactory#32]
### 你觉得框架有什么不足之处？【必答】

这样我的控制台会很乱，会和有用的信息混在一起

### issue 是否有人曾提过类似的建议？【必答】

是

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### 你觉得该怎么去完善会比较好？【非必答】

这块警告没有实质性的作用可以去掉

**Comment by getActivity** [comment]
小伙子，代码堆栈呢？

**Comment by GuangNian10000** [comment]
![image](https://github.com/getActivity/GsonFactory/assets/44353535/beee35d8-2ded-4bb8-b0f3-ab3737f4d2e1)
[未命名.txt](https://github.com/getActivity/GsonFactory/files/13405377/default.txt)

**Comment by GuangNian10000** [comment]
每次调用，控制台就会被刷屏

**Comment by getActivity** [comment]
@GuangNian10000 小伙子，我排查了这个问题，最终锁定是框架在反射创建 `kotlin data class` 类的 Bug，但是由于工作繁忙，我可能要到星期六日才有空处理这个问题。

**Comment by getActivity** [comment]
[GsonFactory-9.2.aar.zip](https://github.com/getActivity/GsonFactory/files/13464468/GsonFactory-9.2.aar.zip)

**Comment by getActivity** [comment]
小伙子，问题修复了，你可以下载上面的包试试看，另外还需要加入以下依赖：

```groovy
dependencies {
    // Kotlin 反射依赖，用于反射 Kotlin data class 类对象
    implementation 'org.jetbrains.kotlin:kotlin-reflect:1.5.10'
}
```

你试试看问题有没有被解决，如果没有的话，请及时反馈给我

**Comment by GuangNian10000** [comment]
已经好了谢谢轮子哥
