### ISSUE TITLE
[Bug]：9.0升级9.2

### ISSUE THREAD

**Issue by Summer-Android** [getActivity/GsonFactory#35]
### 框架版本【必填】

9.2

### 问题描述【必填】

当我调用接口时返回错误：
`ApiResponse#data`，后台返回的条目类型为：`BEGIN_OBJECT`

### 复现步骤【必填】

使用 `Retrofit.Builder().addConverterFactory(GsonConverterFactory.create(GsonFactory.getSingletonGson()))`

调用接口：

```kotlin
suspend fun login(@Body request: LoginRequest): ApiResponse<String>
```

后台返回值：

```kotlin
{
    "code" : 0,
    "data" : "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUz",
    "extra" : null,
    "message" : "success",
    "path" : null,
    "timestamp" : 1702881400175
}
```

ApiResponse实体类：

```kotlin
data class ApiResponse<T>(
    val code: Int?,
    val data: T?,
    val extra: Extra?,
    val message: String?,
    val path: String?,
    val timestamp: Any?,
    val version: String?,
) : BaseResponse<T>() {

    override fun isSuccess(): Boolean = code == 0

    override fun getResponseCode(): Int = code ?: -1

    override fun getResponseData(): T? = data

    override fun getResponseExtra(): Extra? = extra

    override fun getResponseMessage(): String? = message

    override fun getResponsePath(): String? = path

    override fun getResponseTimestamp(): Any? = timestamp

    override fun getResponseVersion(): String? = version
}
```

```kotlin
abstract class BaseResponse<T> {
    abstract fun isSuccess(): Boolean

    abstract fun getResponseCode(): Int

    abstract fun getResponseData(): T?

    abstract fun getResponseExtra(): Extra?

    abstract fun getResponseMessage(): String?

    abstract fun getResponsePath(): String?

    abstract fun getResponseTimestamp(): Any?

    abstract fun getResponseVersion(): String?
}
```

```kotlin
data class Extra(
    val errorMsg: String?
)
```

### 是否必现【必填】

是

### 项目 targetSdkVersion【必填】

33

### 出现问题的手机信息【必填】

小米mix2、逍遥模拟器(android 9版本)

### 出现问题的安卓版本【必填】

Android 9

### 问题信息的来源渠道【必填】

自己遇到的

### 是部分机型还是所有机型都会出现【必答】

目前仅测试小米mix2、逍遥模拟器(android 9版本)

### 框架最新的版本是否存在这个问题【必答】

是

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

### 是否可以通过 Demo 来复现该问题【必答】

是

**Comment by getActivity** [comment]
* 小伙子，我在 demo 中用下面这段代码是正常的，复现不了你说的这个问题

```java
Context context = InstrumentationRegistry.getInstrumentation().getContext();
String json = getAssetsString(context, "TestJson.json");
ApiResponse<String> dataClassBean = mGson.fromJson(json, stringApiResponse.getClass());
Log.i(TAG, mGson.toJson(dataClassBean));
```

**Comment by getActivity** [comment]
> `当我调用接口时返回错误：ApiResponse#data，后台返回的条目类型为：BEGIN_OBJECT`

小伙子，你出现的报错是走的哪个方法？onParseListException 还是 onParseMapException？

**Comment by Summer-Android** [comment]
> > `当我调用接口时返回错误：ApiResponse#data，后台返回的条目类型为：BEGIN_OBJECT`
> 
> 小伙子，你出现的报错是走的哪个方法？onParseListException 还是 onParseMapException？

**Comment by Summer-Android** [comment]
> > `当我调用接口时返回错误：ApiResponse#data，后台返回的条目类型为：BEGIN_OBJECT`
> 
> 小伙子，你出现的报错是走的哪个方法？onParseListException 还是 onParseMapException？

ApiResponse<List<Entity>> 为list时就会报错onParseListException

**Comment by getActivity** [comment]
<img width="1024" alt="image" src="https://github.com/getActivity/GsonFactory/assets/28616817/7c151c5f-36c6-4b7d-bbb0-b0f3473c9f16">

**Comment by getActivity** [comment]
小伙子，框架的远程依赖已经更新了，留意下更新。
