### ISSUE TITLE
[Bug]：升级到 9.3 直接无法解析

### ISSUE THREAD

**Issue by xuxinjiang** [getActivity/GsonFactory#36]
### 框架版本【必填】

v9.3

### 问题描述【必填】

从v9.0升级v9.3直接无法解析了 炸了
![image](https://github.com/getActivity/GsonFactory/assets/41047773/b4e30b58-0dfc-4268-bd31-ebe4ee8ce4a9)

### 复现步骤【必填】

所有接口都解析不了 9.0正常

### 是否必现【必填】

是

### 项目 targetSdkVersion【必填】

23

### 出现问题的手机信息【必填】

小米

### 出现问题的安卓版本【必填】

13

### 是部分机型还是所有机型都会出现【必答】

跟机型没关系

### 框架最新的版本是否存在这个问题【必答】

未选择

### 框架文档是否提及了该问题【必答】

未选择

### 是否已经查阅框架文档但还未能解决的【必答】

未选择

### issue 列表中是否有人曾提过类似的问题【必答】

未选择

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

未选择

### 是否可以通过 Demo 来复现该问题【必答】

未选择

### 提供报错堆栈

```text
![image](https://github.com/getActivity/GsonFactory/assets/41047773/b4e30b58-0dfc-4268-bd31-ebe4ee8ce4a9)
```

### 提供截图或视频

![image](https://github.com/getActivity/GsonFactory/assets/41047773/b4e30b58-0dfc-4268-bd31-ebe4ee8ce4a9)

### 提供解决方案

![image](https://github.com/getActivity/GsonFactory/assets/41047773/b4e30b58-0dfc-4268-bd31-ebe4ee8ce4a9)

**Comment by xuxinjiang** [comment]
你的框架都报错了 ![image](https://github.com/getActivity/GsonFactory/assets/41047773/6fb38fb0-7c55-4a66-aabc-c8cb1050d996)

**Comment by xuxinjiang** [comment]
{"code":2000,"msg":"success","data":{"current_page":1,"data":[{"exchange_id":18,"point":100,"sort":1,"created_at":"1688352702","state":1,"name":"测试商品","image":"https:\/\/voopoo-test.oss-cn-shenzhen.aliyuncs.com\/admin\/202307\/03\/534323142056767488.png","stock":10,"price":"1220.00","buy_status":1},{"exchange_id":17,"point":10,"sort":1,"created_at":"1688104916","state":1,"name":"洋甘菊护手霜女滋润保湿便携嫩白补水小巧随身小雏菊防裂秋冬礼盒","image":"https:\/\/voopoo-test.oss-cn-shenzhen.aliyuncs.com\/admin\/202302\/23\/487323207402070016.png","stock":59,"price":"1231.00","buy_status":1},{"exchange_id":16,"point":1200,"sort":1,"created_at":"1688094981","state":1,"name":"VINCI POD ROYAL EDITION","image":"https:\/\/voopoo-test.oss-cn-shenzhen.aliyuncs.com\/admin\/202306\/30\/533243702870499328.png","stock":1,"price":"100.00","buy_status":1},{"exchange_id":12,"point":12,"sort":0,"created_at":"1688094762","state":1,"name":"DRAG NANO2","image":"https:\/\/voopoo-test.oss-cn-shenzhen.aliyuncs.com\/admin\/202306\/25\/531415990442754048.png","stock":940,"price":"399.00","buy_status":1}],"first_page_url":"http:\/\/192.168.3.163:9502\/exchange\/goodsList?page=1","from":1,"last_page":1,"last_page_url":"http:\/\/192.168.3.163:9502\/exchange\/goodsList?page=1","next_page_url":null,"path":"http:\/\/192.168.3.163:9502\/exchange\/goodsList","per_page":20,"prev_page_url":null,"to":4,"total":4}}

**Comment by xuxinjiang** [comment]
![image](https://github.com/getActivity/GsonFactory/assets/41047773/482c0162-5e15-411d-9ecb-19edb696c660)

**Comment by xuxinjiang** [comment]
新版没法用

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，打回的原因如下：

* 没有严格按照 issue 模板填写问题

请重新提一个 issue 并纠正以上问题
