### ISSUE TITLE
9.0升级9.3[Bug]：

### ISSUE THREAD

**Issue by xuxinjiang** [getActivity/GsonFactory#38]
### 框架版本【必填】

v9.3

### 问题描述【必填】

9.0升级9.3后 解析报错无法解析

### 复现步骤【必填】

![image](https://github.com/getActivity/GsonFactory/assets/41047773/7e376c00-b087-4d45-a91f-c48d7c8adf32)
![image](https://github.com/getActivity/GsonFactory/assets/41047773/c86468ef-5488-49e0-a644-8436661b3360)

### 是否必现【必填】

未选择

### 项目 targetSdkVersion【必填】

23

### 出现问题的手机信息【必填】

小米青春11

### 出现问题的安卓版本【必填】

13

### 是部分机型还是所有机型都会出现【必答】

跟机型没关系

### 框架最新的版本是否存在这个问题【必答】

未选择

### 框架文档是否提及了该问题【必答】

未选择

### 是否已经查阅框架文档但还未能解决的【必答】

未选择

### issue 列表中是否有人曾提过类似的问题【必答】

未选择

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

未选择

### 是否可以通过 Demo 来复现该问题【必答】

未选择

### 提供报错堆栈

```text
{"code":2000,"msg":"success","data":{"token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJwaHBlcjY2Ni9qd3QiLCJ1c2VyX2lkIjoiMTIiLCJqd3Rfc2NlbmUiOiJkZWZhdWx0IiwianRpIjoiZGVmYXVsdF82NTk0ZDgzMjAzZTY3Ni4xOTQyNzk5OCIsImlhdCI6MTcwNDI1MzQ5MCwibmJmIjoxNzA0MjUzNDkwLCJleHAiOjE3MzYzOTQyOTB9.DeUkeOJslxiraqmuw5tnXQj0Qknh7OH-05ZoUiWJRSo","user_info":{"user_id":"12","mobile":"817612703911","username":"Ocean1234567890","regdate":"","avatar":"https:\/\/sg-small.voopoo.com.cn\/voopoo-club\/portrait\/202311\/07\/4d03b89f443b0b4d48f06497e9ec882e1699340148943.jpg","recommender":"","last_login_time":1704253490,"created_at":1639551834,"updated_at":1704253490,"role_id":1,"invite_num":0,"fcm_token":"d-MA5kjATc-rFBPGp76YOt:APA91bFSs1lT5XuCIuuaLOjofXcMfu1jAbbSuVkzj08RtrSATvDWkGKAviZofqt71Znq2HWWCFxA4MZ1ZaRZmUAvLUPVpi94A-sQhtcNVVvzTqdHvD2LSs6mdxyO7zJVmkfNWycXV380","salt":"a31d43","posts":25,"followers":12,"birth_year":1990,"birth_month":1,"birth_day":1,"gender":2,"is_gray":0,"email":"","deleted_at":null,"password":"6f5bae4c240b5dfef0d71c9d357f1372","platform":"2","last_ip":"192.168.12.212","info_status":1,"source":1,"avatar_status":1,"reg_ip":"103.162.172.86","app_version":"2.0.4","last_visit_time":1704253476}}}
```

### 提供截图或视频

![image](https://github.com/getActivity/GsonFactory/assets/41047773/59472757-9db1-45e1-9d74-9f9956f1c985)

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，打回的原因如下：

* [没有严格按照 issue 模板填写问题](https://github.com/getActivity/IssueTemplateGuide)

<img width="1104" alt="image" src="https://github.com/getActivity/GsonFactory/assets/28616817/b98fc300-6609-4736-9b3d-d3f0e0726111">

<img width="546" alt="image" src="https://github.com/getActivity/GsonFactory/assets/28616817/250d4060-9175-456d-9850-93b257a87e06">

请重新提一个 issue 并纠正以上问题
