### ISSUE TITLE
服务端没有返回相应的字段数据

### ISSUE THREAD

**Issue by tiamosu** [getActivity/GsonFactory#4]
`Class Test { 
String name;
String age;
}`

您好，请问下这么一个例子，服务端只有返回name 这个字段数据，导致age为null，（反序列化时，类中有但Json中没有的字段将设值为null。）我想对age进行不为null处理，应该怎么做呢

**Comment by getActivity** [comment]
```java
Class Test {
    String name;
    String age = "28";
}
```

**Comment by getActivity** [comment]
小伙子，你可以这样写试试看

**Comment by tiamosu** [comment]
> 小伙子，你可以这样写试试看

设置了默认值还是为null =-=

**Comment by getActivity** [comment]
小伙子，我试了一下，没有你说的这个问题，需要麻烦你下载一下源码，然后 debug 排查一下是哪行代码设置为空的。

**Comment by tiamosu** [comment]
> > 小伙子，你可以这样写试试看
> 
> 设置了默认值还是为null =-=



> > 小伙子，你可以这样写试试看
> 
> 设置了默认值还是为null =-=



> > 小伙子，你可以这样写试试看
> 
> 设置了默认值还是为null =-=

@Keep
@Parcelize
data class FriendResponse(
    val data: @RawValue List<FriendBean>,
    val test: String = "hello",
) : Parcelable

@Keep
@Parcelize
data class FriendBean(
    val id: Int = 0,
    val link: String? = null,
    val name: String? = null,
    val order: Int = 0,
    val visible: Int = 0,
) : Parcelable

> 小伙子，我试了一下，没有你说的这个问题，需要麻烦你下载一下源码，然后 debug 排查一下是哪行代码设置为空的。

好的，谢谢，我先看看

**Comment by tiamosu** [comment]
> 小伙子，我试了一下，没有你说的这个问题，需要麻烦你下载一下源码，然后 debug 排查一下是哪行代码设置为空的。

好的，谢谢，我这边看看

**Comment by tiamosu** [comment]
> 小伙子，我试了一下，没有你说的这个问题，需要麻烦你下载一下源码，然后 debug 排查一下是哪行代码设置为空的。

您好，我这边测试了下，给参数设定默认值，java是正常的，kotlin还是为null，这个有什么需要注意的么

**Comment by tiamosu** [comment]
> > 小伙子，我试了一下，没有你说的这个问题，需要麻烦你下载一下源码，然后 debug 排查一下是哪行代码设置为空的。
> 
> 您好，我这边测试了下，给参数设定默认值，java是正常的，kotlin还是为null，这个有什么需要注意的么

https://www.wanandroid.com/friend/json 用的这个接口

实体类如下：
@Keep
@Parcelize
data class FriendResponse(
    val data: @RawValue List<FriendBean>,
    val test: String = "hello",
) : Parcelable

@Keep
@Parcelize
data class FriendBean(
    val id: Int = 0,
    val link: String? = null,
    val name: String? = null,
    val order: Int = 0,
    val visible: Int = 0,
) : Parcelable

**Comment by tiamosu** [comment]
> > 小伙子，我试了一下，没有你说的这个问题，需要麻烦你下载一下源码，然后 debug 排查一下是哪行代码设置为空的。
> 
> 您好，我这边测试了下，给参数设定默认值，java是正常的，kotlin还是为null，这个有什么需要注意的么

查到问题所在了，Gson解析需要一个空参构造，而kotlin如果构造中每个参数都有默认值的时候，会有一个空参，并且会正确的将默认值赋值。所以Gson可以正常解析。如果kotlin的构造有参数没有默认值，就会出此问题。-_-||
谢谢您的耐心解答
