### ISSUE TITLE
[疑惑]：为啥fastjson解析的是正常的，本框架解析的不一样

### ISSUE THREAD

**Issue by JasonYinH** [getActivity/GsonFactory#40]
### 问题描述【必填】

比如字段  attitude、collectTime

![image](https://github.com/getActivity/GsonFactory/assets/40187930/4a80dfdc-dccb-446b-acf0-908fbfd1d37d)
![image](https://github.com/getActivity/GsonFactory/assets/40187930/aa6eed51-eb66-488b-b60e-d3f178c46a70)
![image](https://github.com/getActivity/GsonFactory/assets/40187930/3511c031-2a15-4506-bbb1-b661a5cb330e)
![image](https://github.com/getActivity/GsonFactory/assets/40187930/29394b22-ee4b-4aa4-a5ec-5bfd05919259)
![image](https://github.com/getActivity/GsonFactory/assets/40187930/84552692-2da9-46e9-838a-153e4954e4fd)

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by JasonYinH** [comment]
今天想着替换fastJson的，框架版本都是最新的
![image](https://github.com/getActivity/GsonFactory/assets/40187930/85b0560d-5567-45d2-916a-75fedd29e345)

**Comment by getActivity** [comment]
小伙子，我无法复制你图片上面的代码，另外你图片上面的代码不完整，请提供完整且可复现的代码到这里来。

**Comment by JasonYinH** [comment]
AbnormalJson.json

**Comment by JasonYinH** [comment]
assets文件里的资源
`
{
  "attitude": 2,
  "collectTime": 1710150586000
}
`
activity代码
`
  val json: String = getAssetsString(this, "AbnormalJson.json")
        val mGson = GsonFactory.getSingletonGson()
        val jsonBean = mGson.fromJson(json, aaaa::class.java)
        Log.e("xxx", "" + mGson.toJson(jsonBean))

        val beanToMap = mGson.fromJson(mGson.toJson(jsonBean), MutableMap::class.java)
        Log.e("xxxbb", "" + beanToMap)
`
aaaa类
`
class aaaa {
    private var attitude: Int = 0
    private var collectTime: Long = 0L
    override fun toString(): String {
        return "aaaa(attitude=$attitude, collectTime=$collectTime)"
    }


}
`

**Comment by JasonYinH** [comment]
![image](https://github.com/getActivity/GsonFactory/assets/40187930/d9c0933e-386b-4e9c-a936-f09790ed8713)

**Comment by JasonYinH** [comment]
https://mikechen.cc/28914.html  用的第一种

**Comment by JasonYinH** [comment]
![image](https://github.com/getActivity/GsonFactory/assets/40187930/f91d14cc-86e2-467a-93e1-e66b5a5b2ece)
要是用这种反射的方法，将对象转为map就没事了

**Comment by getActivity** [comment]
<img width="1070" alt="image" src="https://github.com/getActivity/GsonFactory/assets/28616817/2d046762-a1e4-4981-be4d-d5f99c3c3dc3">

<img width="813" alt="image" src="https://github.com/getActivity/GsonFactory/assets/28616817/a0896d3f-7134-4585-afdf-2414c548d511">

**Comment by getActivity** [comment]
<img width="623" alt="image" src="https://github.com/getActivity/GsonFactory/assets/28616817/18510770-777f-4ad3-86f9-76579b6f2560">

**Comment by getActivity** [comment]
小伙子，经过核实和验证，确实有这个问题，这是由于 Gson 内部将不指定类型的数值统一解析成 double 类型导致的，`1710126441000` 这个数值会被科学计数法转换成 `1.71E+12`，但是不代表这样的数值有问题，这两种计数严格意义上讲都没有问题，都是相等的，只不过你更想要显示全数值的那种，而非科学计数值，解决这个问题也很简单，我在框架内部自定义了 `ToNumberStrategy` 接口策略，对后台返回的数值接收类型进行了优化，如果是浮点数，则用 double 类型装载，如果是整数，则用 int 类型或者 long 类型装载。

<img width="904" alt="image" src="https://github.com/getActivity/GsonFactory/assets/28616817/807db10a-b9a0-42a6-ac09-b3bbd951532d">

**Comment by getActivity** [comment]
[GsonFactory-9.6.aar.zip](https://github.com/getActivity/GsonFactory/files/14560660/GsonFactory-9.6.aar.zip)

**Comment by getActivity** [comment]
小伙子，你可以用上面的 aar 包试一下看问题是否被解决？

**Comment by JasonYinH** [comment]
佬，用9.6的包解决了，感谢佬的解决

**Comment by zqwxmao** [comment]
佬也太牛太细了~ mark
