### ISSUE TITLE
8.0版本 jitpack无法引用依赖

### ISSUE THREAD

**Issue by rejigtian** [getActivity/GsonFactory#41]
### 框架版本【必填】

8.0

### 问题描述【必填】

https://jitpack.io/com/github/getActivity/GsonFactory/8.0/build.log
3月25的打包失败，无法引用依赖

### 复现步骤【必填】

直接依赖8.0版本错误

### 是否必现【必填】

是

### 项目 targetSdkVersion【必填】

33

### 出现问题的手机信息【必填】

无

### 出现问题的安卓版本【必填】

无

### 问题信息的来源渠道【必填】

自己遇到的

### 是部分机型还是所有机型都会出现【必答】

所有

### 框架最新的版本是否存在这个问题【必答】

否

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

否

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

### 是否可以通过 Demo 来复现该问题【必答】

否

**Comment by rejigtian** [comment]
暂时修改为aar依赖。因为直接升级有风险，后续制定了升级计划。
不过还是希望能重新编译一下，看日志应该只是网络问题导致8.0包没出来。

**Comment by getActivity** [comment]
https://jitpack.io/#getActivity/GsonFactory

**Comment by getActivity** [comment]
<img width="1015" alt="image" src="https://github.com/getActivity/GsonFactory/assets/28616817/959a7159-14c4-4d24-b11a-b2026726386b">

**Comment by getActivity** [comment]
<img width="990" alt="image" src="https://github.com/getActivity/GsonFactory/assets/28616817/0907523c-f229-48af-8f93-10889abf01da">

**Comment by getActivity** [comment]
小伙子，针对你说的这个问题，我进行了核实，确实存在这个问题，目前我已经进行了重新构建，你可以重新试试看行不行。

**Comment by rejigtian** [comment]
已经好了，多谢
