### ISSUE TITLE
[Bug]：result返回为空时出现java.lang.ClassCastException异常，具体返回格式看描述

### ISSUE THREAD

**Issue by mstains** [getActivity/GsonFactory#45]
### 框架版本【必填】

9.6

### 问题描述【必填】

{"message":"操作成功","code":"A000","result":{"count":"15"}}

{"message":"操作成功","code":"A000","result":null}
java.lang.ClassCastException: java.lang.Object cannot be cast to com.xxxx.ben.xxxx

### 复现步骤【必填】

{"message":"操作成功","code":"A000","result":null} result为null时必现

### 是否必现【必填】

是

### 项目 targetSdkVersion【必填】

33

### 出现问题的手机信息【必填】

红米K30Pro

### 出现问题的安卓版本【必填】

12

### 问题信息的来源渠道【必填】

自己遇到的

### 是部分机型还是所有机型都会出现【必答】

全部

### 框架最新的版本是否存在这个问题【必答】

是

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

### 是否可以通过 Demo 来复现该问题【必答】

是

**Comment by getActivity** [comment]
<img width="341" alt="image" src="https://github.com/getActivity/GsonFactory/assets/28616817/bf6ea5af-ced2-4861-b817-3dfc320c05bf">

<img width="603" alt="image" src="https://github.com/getActivity/GsonFactory/assets/28616817/d045890e-4358-4e03-975d-217a2db394de">

<img width="968" alt="image" src="https://github.com/getActivity/GsonFactory/assets/28616817/47e577d5-b17d-43b3-9862-e89f932fe83c">

**Comment by getActivity** [comment]
小伙子，提供你提供的复现步骤，我无法复现此问题，你确认一下复现的步骤是否有问题？或者你提供一个 Demo 工程上传到这里来，我这边来做测试。

**Comment by mstains** [comment]
![Snipaste_2024-05-06_19-03-13](https://github.com/getActivity/GsonFactory/assets/39607750/ef353209-e353-45d3-ac44-8d3747a252a2)
![Snipaste_2024-05-06_19-03-25](https://github.com/getActivity/GsonFactory/assets/39607750/bce06bb0-44d2-436e-950c-89d3140bfff3)
Retrofit 配置
Retrofit.Builder().addCallAdapterFactory(RxJava2CallAdapterFactory.create())
            .addConverterFactory(ScalarsConverterFactory.create())
            .addConverterFactory(GsonConverterFactory.create(GsonFactory.getSingletonGson()))
            .client(createOkHttpClient(cache, HttpConst.LONG_HTTP_TIMEOUT)).baseUrl(baseUrl).build()

**Comment by getActivity** [comment]
@mstains 小伙子，你直接提供一个可供复现的 Demo 工程给到我。

**Comment by mstains** [comment]
[Uploading GsonFactoryApplication.zip…]()
这是写的demo工程

**Comment by getActivity** [comment]
@mstains 小伙子，你确定 Demo 工程上传成功了？

**Comment by mstains** [comment]
[GsonFactoryApplication.zip](https://github.com/getActivity/GsonFactory/files/15247956/GsonFactoryApplication.zip)
重新上传

**Comment by getActivity** [comment]
<img width="1680" alt="image" src="https://github.com/getActivity/GsonFactory/assets/28616817/a1dabbae-2ee8-4a02-a3cd-e3d82b8674c0">

**Comment by getActivity** [comment]
小伙子，`result` 没有加 `?` 表示这个字段一定不为 `null`，但是后台返回 `null`，你不觉得这样定义有问题？
