### ISSUE TITLE
[疑惑]：

### ISSUE THREAD

**Issue by 15110052956** [getActivity/GsonFactory#47]
### 问题描述【必填】

大佬，我能在整个解析过程中，获取到一个在JavaBean中未定义的属性值吗？比如后端返回的结构体中统一增加了一个tr的字段，但是我所有的Java Bean (Data Class)都没有定义这个字段，按照Gson的解析流程会将未定义的字段都过滤掉，但是我这时想要拿到这个tr字段，应该如何做呢？

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

否

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by 15110052956** [comment]
准确的描述应该是及拿到对应的数据，并且能否在解析后的JavaBean中添加一个对应的tr属性

**Comment by getActivity** [comment]
<img width="421" alt="image" src="https://github.com/user-attachments/assets/f9684687-f9b6-4706-9fe9-2610dc474134">

小伙子，该 issue 被打回，打回的原因如下：

* 请仔细查阅框架文档之后，确定没有之后再给我提 issue

请重新提一个 issue 并纠正以上问题
