### ISSUE TITLE
数组没有容错，“[ ]” 这种情况

### ISSUE THREAD

**Issue by jarvan11** [getActivity/GsonFactory#5]
如题，发现数组没有容错，“[ ]” 这种情况，

看文档，array只容错如下这几种：
{}、""、false、0

**Comment by getActivity** [comment]
数组本身的数据格式不就是 `[]` ？

**Comment by jarvan11** [comment]
> 数组本身的数据格式不就是 `[]` ？还用得着容错？

就是接口抽风，本来就是数组的，有些返回 [ ] ，有些返回 ”[ ]“

**Comment by getActivity** [comment]
你是说 `“[]”` 是吧？这种是可以容错的

**Comment by getActivity** [comment]
如果没有什么问题，我就先关闭 issue 了，如果你还有其他问题随时欢迎再提 issue 给我
