### ISSUE TITLE
弱弱的问一句,这个框架该怎么使用,大佬

### ISSUE THREAD

**Issue by lydlovezjr** [getActivity/GsonFactory#6]

**Comment by lydlovezjr** [comment]
使用文档只有简单的两句
// 获取单例的 Gson 对象（已处理容错）
Gson gson = GsonFactory.getSingletonGson();

// 创建一个 Gson 构建器（已处理容错）
GsonBuilder gsonBuilder = GsonFactory.createGsonBuilder();

**Comment by getActivity** [comment]
* 请使用框架返回的 Gson 对象来代替项目中的 Gson 对象

```java
// 获取单例的 Gson 对象（已处理容错）
Gson gson = GsonFactory.getSingletonGson();
```

* 因为框架中的 Gson 对象已经对解析规则进行了容错处理

**Comment by lydlovezjr** [comment]
已用上,很强
