### ISSUE TITLE
BigDecimalTypeAdapter 有BUG

### ISSUE THREAD

**Issue by op123355569** [getActivity/GsonFactory#7]
`String result = in.nextString();`
`if (result == null || "".equals(result)) {`
        ` return new BigDecimal(0);`
`}`
`return new BigDecimal(in.nextString());`

**return new BigDecimal(in.nextString());**
应改为：
**return new BigDecimal(result);**

**Comment by getActivity** [comment]
已经纠正，多谢小伙子的提醒

**Comment by getActivity** [comment]
[gson-factory.aar.zip](https://github.com/getActivity/GsonFactory/files/6039946/gson-factory.aar.zip)

**Comment by getActivity** [comment]
这个 Bug 会在下个版本修复好，小伙子你要是着急用的话可以先用这个 aar 包

**Comment by getActivity** [comment]
小伙子，问题已经修复，更新到 5.0 版本即可

**Comment by op123355569** [comment]
> 小伙子，问题已经修复，更新到 5.0 版本即可

好的，谢啦
