### ISSUE TITLE
谢谢轮子哥解决了我的问题！！

### ISSUE THREAD

**Issue by bjshtech** [getActivity/GsonFactory#8]
我们登录接口后台应该返回实体对象类型，在code码错误时，后台返回的字符串，导致我这一直报错，在网上找了好多都解决不了，用了轮子哥这个直接帮我解决了，轮子哥太强大了！！

**Comment by getActivity** [comment]
![](https://user-images.githubusercontent.com/28616817/115491235-2d11d380-a292-11eb-9d31-1722d2d996a4.png)

**Comment by getActivity** [comment]
多谢小伙子的喜欢，好用的话，记得给 Star 再走，下次才能有更多的人发现这个库。
