### ISSUE TITLE
在库里面怎样解决Gson解析数据用map接收时int自动转化为double问题

### ISSUE THREAD

**Issue by hopelesszxq** [getActivity/GsonFactory#9]
Map map=new HashMap<>();
        map.put("a",1);
        map.put("b",2);
        String json=mGson.toJson(map);
        Map result=mGson.fromJson(json,Map.class);

result中的a值为1.0,b为2.0

**Comment by getActivity** [comment]
小伙子，你这个问题跟框架好像没啥关系吧？

**Comment by getActivity** [comment]
框架只能帮你处理容错的问题，这个问题不属于 Json 容错的范畴之内。
